/* eslint-disable @typescript-eslint/camelcase */
export default {
  'aggregazioni-logiche-collegate': 'Fondi collegati',
  estremo_remoto: 'Estremo remoto',
  estremo_recente: 'Estremo recente',
  // FIXME: duplicate
  // 'consistenza.quantita': 'Consistenza',
  // 'consistenza.unitaMisura': 'Consistenza - unità di misura',
  produzione: 'Soggetto produttore',
  'conservazione.soggettoConservatore': 'Soggetto conservatore',
  'soggettoConservatore.soggettoConservatoreAttuale': 'Soggetto conservatore',
  'conservazione.tipoResponsabilita': 'Soggetto conservatore - tipo responsabilità',
  'conservazione.parteConservata': 'Parte conservata',
  'conservazione.causeAcquisizione': 'Storia della custodia',
  descrizione_interna: 'Descrizione',
  altra_documentazione: 'Materiali correlati',
  storia_ordinamenti: 'Storia degli ordinamenti',
  descrizione_esterna: 'Descrizione esterna',
  stato_conservazione: 'Stato di conservazione',
  statoConservazione: 'Stato di conservazione',
  storia_ubicazioni: 'Storia delle ubicazioni',
  storiaUbicazioni: 'Storia delle ubicazioni',
  // FIXME: duplicate
  // 'corredoRicerca.tipologia': 'Strumento di corredo e ricerca',
  // 'corredoRicerca.riferimento': 'Strumento di corredo e ricerca - riferimento',
  // 'corredoRicerca.descrizione': 'Strumento di corredo e ricerca - descrizione',
  'altra_segnatura.tipologia': 'Altra segnatura - tipologia',
  'altra_segnatura.numerazione': 'Altra segnatura',
  intitolazione: '',
  'altra_intitolazione.tipologia': 'Altra intitolazione - tipologia',
  'altra_intitolazione.intitolazione': 'Altra intitolazione',
  definizione_tipologia: 'Tipologia',
  supporto: 'Supporto',
  'legatura.tipologia': 'Legatura',
  'legatura.epoca': 'Legatura - epoca ',
  'legatura.datazione': 'Legatura - datazione',
  'condizionamento.tipologia': 'Condizionamento',
  'condizionamento.materia': 'Condizionamento - materia',
  'condizionamento.epoca': 'Condizionamento - epoca',
  'condizionamento.datazione': 'Condizionamento - datazione',
  altezza: 'Altezza (mm.)',
  larghezza: 'Larghezza (mm.)',
  spessore: 'Spessore (mm.)',
  'consistenza.quantita': 'Consistenza',
  'consistenza.unitaMisura': 'Consistenza - unità di misura',
  'numerazione.tipoNumerazione': 'Numerazione - tipo',
  'numerazione.numerazione': 'Numerazione ',
  'numerazione.epoca': 'Numerazione - epoca ',
  'numerazione.datazione': 'Numerazione - datazione',
  'descrizioneEsterna.tipologia': 'Descrizione esterna',
  'descrizioneEsterna.posizione': 'Descrizione esterna - posizione',
  'descrizioneEsterna.trascrizione': 'Descrizione esterna - trascrizione',
  'statoConservazione.statoConservazione': 'Stato di conservazione',
  'descrizioneInterna.tipologiaDocumentaria': 'Tipologia documentaria',
  'descrizioneInterna.descrizione': 'Descrizione',
  'descrizioneInterna.trascrizione': 'Trascrizione',
  'documentazioneTestuale.tipologia': 'Presenza di documentazione testuale',
  'documentazioneTestuale.lingua': 'Presenza di documentazione testuale - lingua',
  'documentazioneGrafica.tipologia': 'Presenza di documentazione grafica',
  'documentazioneGrafica.tecnicaEsecutiva': 'Presenza di documentazione grafica - tecnica esecutiva',
  'documentazioneCopia.tipologia': 'Presenza di documentazione in copia',
  'documentazioneCopia.epoca': 'Presenza di documentazione in copia - epoca',
  'strumentoCorredoInterno.tipologia': 'Strumenti di corredo interni',
  'strumentoCorredoInterno.oggetto': 'Strumenti di corredo interni - oggetto',
  'strumentoCorredoInterno.epoca': 'Strumenti di corredo interni - epoca',
  'corredoRicerca.tipologia': 'Strumento di corredo e ricerca',
  'corredoRicerca.riferimento': 'Strumento di corredo e ricerca - riferimento',
  'corredoRicerca.descrizione': 'Strumento di corredo e ricerca - descrizione',
  'aggregazione-logica.typology': '',
  // FIXME: duplicate
  // struttura_funzioni: 'Funzioni principali',
  'aggregazione-logica': 'Aggregazione logica',
  'oggetto-culturale': 'Oggetto culturale',
  // FIXME: duplicate
  // tipologia: '',
  descrizione: 'Descrizione',
  data_inizio: 'Data di inizio',
  data_fine: 'Data di fine',
  ricorrenza: 'Ricorrenza',
  'altraDenominazione.tipologiaDenominazione': 'Altra denominazione - tipologia',
  'altraDenominazione.altraDenominazione': 'Altra denominazione',
  data_fondazione: 'Data di fondazione',
  data_estinzione: 'Data di estinzione',
  // FIXME: duplicate
  // note_storiche: 'Storia',
  stato: 'Stato',
  regione: 'Regione',
  provincia: 'Provincia',
  comune: 'Comune',
  // FIXME: duplicate
  // note_storiche: 'Descrizione ',
  natura_giuridica: 'Natura giuridica',
  sede: 'Sedi',
  data_istituzione: 'Data di istituzione',
  'data_soppressione  ': 'Data di soppressione',
  note_storiche: 'Storia',
  struttura_funzioni: 'Struttura organizzativa',
  genere: 'Genere',
  altro_luogo: 'Luoghi significativi',
  luogo_nascita: 'Luogo di nascita',
  luogo_morte: 'Luogo di morte',
  data_nascita: 'Data di nascita',
  data_morte: 'Data di morte',
  biografia: 'Biografia',
  tipologia: 'Qualifica - tipologia',
  qualifica: 'Qualifica',

  'AGGREGAZIONE LOGICA': '---',
  'aggregazione-logica.estremo_remoto': 'Estremo remoto',
  'aggregazione-logica.estremo_recente': 'Estremo recente',
  'aggregazione-logica.tipologia': 'Tipologia',
  'aggregazione-logica.numerazione_index': 'Indice di classificazione',
  'aggregazione-logica.altre_denominazioni': 'Altre denominazioni',
  'aggregazione-logica.altre_denominazioni.tipologia': 'Tipologia',
  'aggregazione-logica.altre_denominazioni.denominazione': 'Denominazione',
  'aggregazione-logica.consistenza': 'Consistenza',
  'aggregazione-logica.consistenza.quantita': 'Quantità',
  'aggregazione-logica.consistenza.unitaMisura': 'Unità di misura',
  'aggregazione-logica.produzione': 'Produzione',
  'aggregazione-logica.conservazione': 'Conservazione',

  'aggregazione-logica.soggettoProduttore': 'Soggetto produttore',
  'aggregazione-logica.soggettoConservatore': 'Soggetto conservatore',
  'aggregazione-logica.soggettoConservatore.soggettoConservatoreAttuale': 'Soggetto conservatore',
  'aggregazione-logica.soggettoConservatore.tipoResponsabilita': 'Tipo responsabilità',
  'aggregazione-logica.soggettoConservatore.parteConservata': 'Parte conservata',
  'aggregazione-logica.soggettoConservatore.causeAcquisizione': 'Storia della custodia',

  'aggregazione-logica.conservazione.soggettoConservatore': 'Soggetto conservatore',
  'aggregazione-logica.conservazione.soggettoConservatoreAttuale': 'Soggetto conservatore',
  'aggregazione-logica.conservazione.tipoResponsabilita': 'Tipo di responsabilità',
  'aggregazione-logica.conservazione.parteConservata': 'Parte conservata',
  'aggregazione-logica.conservazione.causeAcquisizione': 'Storia della custodia',
  'aggregazione-logica.descrizione_interna': 'Descrizione',
  'aggregazione-logica.storia_ordinamenti': 'Storia degli ordinamenti',
  'aggregazione-logica.altra_documentazione': 'Materiali correlati',
  'aggregazione-logica.descrizione_esterna': 'Descrizione esterna',
  'aggregazione-logica.storiaUbicazioni.storiaUbicazioni': 'Storia delle ubicazioni',
  'aggregazione-logica.condizioni_consultazione_modalita': 'Modalità di consultazione',
  'aggregazione-logica.condizioni_consultazione_tempi': 'Tempi per la consultazione',
  'aggregazione-logica.corredoRicerca': 'Strumento di corredo e ricerca',
  'aggregazione-logica.corredoRicerca.tipologia': 'Tipologia',
  'aggregazione-logica.corredoRicerca.riferimento': 'Riferimento',
  'aggregazione-logica.corredoRicerca.descrizione': 'Descrizione',
  'aggregazione-logica.statoAttualeConservazione.statoConservazione': 'Stato di conservazione',

  'OGGETTO CULTURALE': '---',
  'oggetto-culturale.estremo_remoto': 'Estremo remoto',
  'oggetto-culturale.estremo_recente': 'Estremo recente',
  'oggetto-culturale.numerazione_index': 'Segnatura principale',
  'oggetto-culturale.altraSegnatura': 'Altra segnatura',
  'oggetto-culturale.altraSegnatura.numerazione': 'Numerazione',
  'oggetto-culturale.altraSegnatura.tipologia': 'Tipologia',
  'oggetto-culturale.altra_intitolazione': 'Altra intitolazione',
  'oggetto-culturale.altra_intitolazione.intitolazione': 'Intitolazione',
  'oggetto-culturale.altra_intitolazione.tipologia': 'Tipologia',
  'oggetto-culturale.definizione_tipologia': 'Tipologia',
  'oggetto-culturale.supporto': 'Supporto',
  'oggetto-culturale.consistenza': 'Consistenza',
  'oggetto-culturale.consistenza.quantita': 'Quantità',
  'oggetto-culturale.consistenza.unitaMisura': 'Unità di misura',
  'oggetto-culturale.descrizioneInterna.descrizione': 'Descrizione',
  'oggetto-culturale.descrizione_interna': 'Descrizione',
  'oggetto-culturale.altezza': 'Altezza (mm.)',
  'oggetto-culturale.larghezza': 'Larghezza (mm.)',
  'oggetto-culturale.spessore': 'Spessore (mm.)',
  'oggetto-culturale.stato_conservazione': 'Stato di conservazione',
  'oggetto-culturale.legatura': 'Legatura',
  'oggetto-culturale.legatura.tipologia': 'Tipologia',
  'oggetto-culturale.legatura.epoca': 'Epoca',
  'oggetto-culturale.legatura.datazione': 'Datazione',
  'oggetto-culturale.condizionamento': 'Condizionamento',
  'oggetto-culturale.condizionamento.tipologia': 'Tipologia',
  'oggetto-culturale.condizionamento.materia': 'Materia',
  'oggetto-culturale.condizionamento.epoca': 'Epoca',
  'oggetto-culturale.condizionamento.datazione': 'Datazione',
  'oggetto-culturale.numerazione': 'Numerazione',
  'oggetto-culturale.numerazione.numerazione': 'Numerazione',
  'oggetto-culturale.numerazione.tipoNumerazione': 'Tipo',
  'oggetto-culturale.numerazione.epoca': 'Epoca',
  'oggetto-culturale.numerazione.datazione': 'Datazione',
  'oggetto-culturale.descrizioneEsterna': 'Descrizione esterna',
  'oggetto-culturale.descrizioneEsterna.tipologia': 'Tipologia',
  'oggetto-culturale.descrizioneEsterna.posizione': 'Posizione',
  'oggetto-culturale.descrizioneEsterna.trascrizione': 'Trascrizione',
  'oggetto-culturale.descrizione_interna_tipologia': 'Tipologia documentaria',
  'oggetto-culturale.descrizione_interna_trascrizione': 'Trascrizione',
  'oggetto-culturale.documentazioneTestuale': 'Presenza di documentazione testuale',
  'oggetto-culturale.documentazioneTestuale.tipologia': 'Tipologia',
  'oggetto-culturale.documentazioneTestuale.lingua': 'Lingua',
  'oggetto-culturale.documentazioneGrafica': 'Presenza di documentazione grafica',
  'oggetto-culturale.documentazioneGrafica.tipologia': 'Tipologia',
  'oggetto-culturale.documentazioneGrafica.tecnicaEsecutiva': 'Tecnica esecutiva',
  'oggetto-culturale.documentazioneCopia': 'Presenza di documentazione in copia',
  'oggetto-culturale.documentazioneCopia.tipologia': 'Tipologia',
  'oggetto-culturale.documentazioneCopia.epoca': 'Epoca',
  'oggetto-culturale.strumentoCorredoInterno': 'Strumenti di corredo interni',
  'oggetto-culturale.strumentoCorredoInterno.tipologia': 'Tipologia',
  'oggetto-culturale.strumentoCorredoInterno.oggetto': 'Oggetto',
  'oggetto-culturale.strumentoCorredoInterno.epoca': 'Epoca',
  'oggetto-culturale.corredoRicerca': 'Strumento di corredo e ricerca',
  'oggetto-culturale.corredoRicerca.tipologia': 'Tipologia',
  'oggetto-culturale.corredoRicerca.riferimento': 'Riferimento',
  'oggetto-culturale.corredoRicerca.descrizione': 'Descrizione',

  'ENTITA COSA NOTEVOLE': '---',
  'cosa notevole.tipologia': 'Tipologia',
  'cosa notevole.descrizione': 'Descrizione',

  'ENTITA EVENTO': '---',
  'evento.tipologia': 'Tipologia',
  'evento.altraDenominazione': 'Altre denominazioni',
  'evento.altraDenominazione.altraDenominazione': 'Denominazione',
  'evento.altraDenominazione.tipologiaDenominazione': 'Tipologia',
  'evento.data_inizio': 'Data di inizio',
  'evento.data_fine': 'Data di fine',
  'evento.ricorrenza': 'Ricorrenza',
  'evento.descrizione': 'Descrizione',

  'ENTITA FAMIGLIA': '---',
  'famiglia.data_fondazione': 'Data di fondazione',
  'famiglia.data_estinzione': 'Data di estinzione',
  'famiglia.altraDenominazione': 'Altre denominazioni',
  'famiglia.altraDenominazione.altraDenominazione': 'Denominazione',
  'famiglia.altraDenominazione.tipologiaDenominazione': 'Tipologia',
  'famiglia.luogo': 'Contesto spaziale',
  'famiglia.note_storiche': 'Storia',

  'ENTITA-LUOGO': '---',
  'luogo.tipologia': 'Tipologia',
  'luogo.altraDenominazione': 'Altre denominazioni',
  'luogo.altraDenominazione.altraDenominazione': 'Denominazione',
  'luogo.altraDenominazione.tipologiaDenominazione': 'Tipologia',
  'luogo.stato': 'Stato',
  'luogo.regione': 'Regione',
  'luogo.provincia': 'Provincia',
  'luogo.comune': 'Comune',
  'luogo.note_storiche': 'Descrizione ',

  'ENTITA-ORGANIZZAZIONE': '---',
  'organizzazione.tipologia': 'Tipologia',
  'organizzazione.natura_giuridica': 'Natura giuridica',
  'organizzazione.data_istituzione': 'Data di istituzione',
  'organizzazione.data_soppressione': 'Data di soppressione',
  'organizzazione.altraDenominazione': 'Altre denominazioni',
  'organizzazione.altraDenominazione.altraDenominazione': 'Denominazione',
  'organizzazione.altraDenominazione.tipologiaDenominazione': 'Tipologia',
  'organizzazione.sede': 'Sedi',
  'organizzazione.note_storiche': 'Storia',
  'organizzazione.struttura_funzioni': 'Struttura organizzativa',

  'ENTITA-PERSONA': '---',
  'persona.luogo_nascita': 'Luogo di nascita',
  'persona.data_nascita': 'Data di nascita',
  'persona.luogo_morte': 'Luogo di morte',
  'persona.data_morte': 'Data di morte',
  'persona.genere': 'Genere',
  'persona.altraDenominazione': 'Altre denominazioni',
  'persona.altraDenominazione.altraDenominazione': 'Denominazione',
  'persona.altraDenominazione.tipologiaDenominazione': 'Tipologia',
  'persona.altro_luogo': 'Luoghi significativi',
  'persona.biografia': 'Biografia',
  'persona.qualifica': 'Qualifica',
  'persona.qualifica.qualifica': 'Qualifica',
  'persona.qualifica.tipologia': 'Tipologia',

  FINE: '---'
};
