name: build-dev
defaults:
  run:
    working-directory: /mnt/c/Projects/n7-frontent-framework/n7-frontend-boilerplate
on: 
  push: 
    tags:        
      - v*
jobs:
  run-build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: |
        npm i  
    - name: Branch name
      id: vars
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
    - name: Update dist
      run: |
        cd ../n7-frontend-boilerplate-dist
        git pull origin master
    - name: npm run build
      run: |
        npm run build
    - name: build dist
      run: |
        git add .
        git commit -m'dist updated to version '
        git push
        git tag -a  ${{ steps.vars.outputs.SOURCE_TAG }} -m 'version  ${{ steps.vars.outputs.SOURCE_TAG }}'
        git push --tags --force
