name: build-dev
defaults:
  run:
    working-directory: /mnt/c/Projects/n7-frontent-framework/n7-frontend-boilerplate
on: 
  push:
    branches:
      - master
jobs:
  run-build:
    runs-on: [self-hosted]
    steps:
    - name: npm install
      run: |
        npm i 
    - name: npm run build
      run: |
        npm run build        
