name: build-dev
defaults:
  run:
    working-directory: /mnt/c/Projects/n7-frontent-framework/n7-frontend-boilerplate
on: 
  push:
    branches:
      - master
jobs:
  run-build:
    runs-on: [self-hosted]
    steps:
    - name: npm install
      run: |
        npm i 
    - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Update dist
        run: |
          cd ../n7-frontend-boilerplate-dist
          git pull origin master
    - name: npm run build
      run: |
        npm run build
    - name: build dist
        run: |
          git add .
          git commit -m'dist updated to version ${{ steps.get_version.outputs.VERSION }}'
          git push
          git tag -a ${{ steps.get_version.outputs.VERSION }} -m'version ${{ steps.get_version.outputs.VERSION }}'
          git push --tags --force
          
