name: Node.js Package

on: 
  push:
    tags:
      - v*

jobs:
  update-changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Move "Unreleased" to new release
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        with:
          version: ${{ steps.get_version.outputs.version }}

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "Changelog updated to ${{ steps.get_version.outputs.version }}"

  push-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install
          npm run build
          npm publish dist/n7-boilerplate-common --access public
          npm publish dist/n7-boilerplate-muruca --access public
          npm publish dist/n7-boilerplate-arianna --access public
          npm publish dist/n7-boilerplate-dataviz --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # publish-common:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm i
  #     - run: npm run build
  #     - run: npm publish dist/n7-boilerplate-common --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # publish-muruca:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm i
  #     - run: npm run build
  #     - run: npm publish dist/n7-boilerplate-muruca --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # publish-arianna:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm i
  #     - run: npm run build
  #     - run: npm publish dist/n7-boilerplate-arianna --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # publish-dataviz:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14
  #         registry-url: https://registry.npmjs.org/
  #     - run: npm i
  #     - run: npm run build
  #     - run: npm publish dist/n7-boilerplate-dataviz --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
