name: Node.js Package

on: 
  push:
    branches: ['feature/module-split']
    # tags:
    #   - v*

jobs:
  publish-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
      - run: npm publish dist/n7-boilerplate-common --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-muruca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
      - run: npm publish dist/n7-boilerplate-muruca --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-arianna:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
      - run: npm publish dist/n7-boilerplate-arianna --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-dataviz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run build
      - run: npm publish dist/n7-boilerplate-dataviz --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}